// -------------------------------------------------------------------------------------------
// Instrumind ThinkComposer CLI
//
// Deterministic, JSON-authoritative synthetic packages for persistence performance testing.
// -------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.IO.Packaging;
using System.Linq;
using System.Security.Cryptography;
using System.Text;

using Instrumind.Common;
using Instrumind.ThinkComposer.Composer;
using Instrumind.ThinkComposer.Composer.JsonInterchange;
using Instrumind.ThinkComposer.Definitor.DomainJsonInterchange;

namespace Instrumind.ThinkComposer.Cli
{
    internal static partial class PersistencePerformance
    {
        private const int SyntheticConceptCount = 5000;
        private const int SyntheticRelationshipCount = 7500;
        private const int SyntheticViewCount = 5;
        private const int SyntheticVisualCount = 15000;
        private const int SyntheticConnectorCount = 15000;

        private const int SyntheticDomainConceptDefinitionCount = 500;
        private const int SyntheticDomainRelationshipDefinitionCount = 250;
        private const int SyntheticDomainTableCount = 125;
        private const int SyntheticDomainFieldsPerTable = 8;
        private const int SyntheticDomainMarkerCount = 250;
        private const int SyntheticDomainLanguageCount = 4;
        private const int SyntheticDomainTemplateCount = 100;

        private const string SyntheticTimestamp = "2000-01-01T00:00:00.0000000Z";
        private const string JsonContentType = "application/json";

        private static void CreateSyntheticComposition(string BaseCompositionPackage,
                                                       string BaseDomainPackage,
                                                       string OutputPackage)
        {
            var CompositionPayload = JsonPackagePersistence.ReadCompositionPackage(BaseCompositionPackage);
            var DomainPayload = JsonPackagePersistence.ReadDomainPackage(BaseDomainPackage);
            if (CompositionPayload.CompositionDocument == null)
                throw new InvalidDataException("The synthetic Composition seed has no /Composition.json payload.");
            if (DomainPayload.DomainDocument == null || DomainPayload.DomainDocument.Domain == null)
                throw new InvalidDataException("The synthetic Composition Domain seed has no /Domain.json payload.");

            var Document = CompositionPayload.CompositionDocument;
            var DomainDocument = DomainPayload.DomainDocument;
            var Definitions = SelectSyntheticDefinitions(DomainDocument);

            DomainDocument.ExportedAtUtc = SyntheticTimestamp;
            Document.ExportedAtUtc = SyntheticTimestamp;
            Document.TargetContext = null;
            Document.Requires = null;
            Document.ImportOptions = null;
            Document.VisualStrategy = null;
            Document.Operations = new List<CompositionJsonOperation>();
            Document.Groups = new List<CompositionJsonGroup>();
            Document.Warnings = new List<string>();

            var CompositionId = StableGuid("synthetic-composition");
            var RootViewId = StableGuid("synthetic-composition-view-0000");
            Document.Composition = new CompositionJsonComposition
            {
                Id = CompositionId,
                Name = "Synthetic JSON Persistence Composition",
                TechName = "Synthetic_JSON_Persistence_Composition",
                Summary = "Deterministic large Composition used by the JSON persistence benchmark.",
                Description = "Generated by ThinkComposer.Cli. Do not edit or commit generated corpus artifacts.",
                TechSpec = "5000 concepts; 7500 relationships; 5 views; 15000 visual representations; 15000 connector records.",
                ViewsPrefix = "View",
                RootViewId = RootViewId,
                ActiveViewId = RootViewId,
                Version = new CompositionJsonVersion
                {
                    VersionSequence = 1,
                    VersionNumber = "1.0.00",
                    Annotation = "Deterministic performance corpus",
                    Creator = "ThinkComposer.Cli",
                    LastModifier = "ThinkComposer.Cli",
                    Creation = SyntheticTimestamp,
                    LastModification = SyntheticTimestamp
                },
                Domain = BuildCompositionDomainContext(DomainDocument, Definitions)
            };

            Document.Ideas = BuildSyntheticConcepts(CompositionId, Definitions);
            Document.Relationships = new List<CompositionJsonRelationship>(SyntheticRelationshipCount);
            Document.Views = new List<CompositionJsonView>(SyntheticViewCount);

            for (var ViewIndex = 0; ViewIndex < SyntheticViewCount; ViewIndex++)
                BuildSyntheticView(Document, ViewIndex, CompositionId, Definitions);

            AssertSyntheticCompositionCounts(Document);

            var CompositionJson = CompositionJsonSerializer.Serialize(Document);
            var DomainJson = DomainJsonSerializer.Serialize(DomainDocument);
            WriteSyntheticPackage(OutputPackage, "composition",
                Document.Composition.Id, Document.Composition.Name, Document.Composition.TechName,
                new SyntheticJsonPart("composition", JsonPackagePersistence.CompositionJsonPartUri,
                                      CompositionJsonDocument.CurrentFormat, CompositionJson),
                new SyntheticJsonPart("embeddedDomain", JsonPackagePersistence.DomainJsonPartUri,
                                      DomainJsonDocument.CurrentFormat, DomainJson));
        }

        private static void CreateSyntheticDomain(string BaseDomainPackage, string OutputPackage)
        {
            var Payload = JsonPackagePersistence.ReadDomainPackage(BaseDomainPackage);
            var Document = Payload.DomainDocument;
            if (Document == null || Document.Domain == null)
                throw new InvalidDataException("The synthetic Domain seed has no /Domain.json payload.");

            Document.ExportedAtUtc = SyntheticTimestamp;
            Document.Domain.Id = StableGuid("synthetic-domain");
            Document.Domain.Name = "Synthetic JSON Persistence Domain";
            Document.Domain.TechName = "Synthetic_JSON_Persistence_Domain";
            Document.Domain.Summary = "Deterministic large Domain used by the JSON persistence benchmark.";
            Document.Domain.Description = "Generated by ThinkComposer.Cli. Do not edit or commit generated corpus artifacts.";
            Document.Domain.TechSpec = "500 concept definitions; 250 relationship definitions; 125 eight-field tables; 250 markers; 4 languages; 100 templates.";
            Document.Domain.CompatibilitySignature = null;
            Document.Operations = new List<DomainJsonOperation>();
            Document.Warnings = new List<string>();

            // Retain only the seed's field data-type identity. The benchmark contract specifies
            // exact final population sizes, so none of the measured collections may retain seed
            // entities in addition to the deterministic synthetic entities below.
            var DataTypeTechName = FindSeedFieldDataType(Document);
            Document.ConceptDefinitions = new List<DomainJsonElement>();
            Document.RelationshipDefinitions = new List<DomainJsonElement>();
            Document.TableDefinitions = new List<DomainJsonElement>();
            Document.MarkerDefinitions = new List<DomainJsonElement>();
            Document.ExternalLanguages = new List<DomainJsonElement>();
            Document.ConceptDefinitionOutputTemplates = new List<DomainJsonElement>();
            Document.RelationshipDefinitionOutputTemplates = new List<DomainJsonElement>();
            Document.RelationshipCompatibility = new List<DomainJsonRelationshipCompatibility>();

            for (var Index = 0; Index < SyntheticDomainConceptDefinitionCount; Index++)
                Document.ConceptDefinitions.Add(CreateSyntheticConceptDefinition(Index));

            for (var Index = 0; Index < SyntheticDomainRelationshipDefinitionCount; Index++)
                Document.RelationshipDefinitions.Add(CreateSyntheticRelationshipDefinition(Index));

            for (var Index = 0; Index < SyntheticDomainTableCount; Index++)
                Document.TableDefinitions.Add(CreateSyntheticTableDefinition(Index, DataTypeTechName));

            for (var Index = 0; Index < SyntheticDomainMarkerCount; Index++)
                Document.MarkerDefinitions.Add(CreateSyntheticMarkerDefinition(Index));

            for (var Index = 0; Index < SyntheticDomainLanguageCount; Index++)
                Document.ExternalLanguages.Add(CreateSyntheticLanguage(Index));

            for (var Index = 0; Index < SyntheticDomainTemplateCount; Index++)
                Document.ConceptDefinitionOutputTemplates.Add(CreateSyntheticTemplate(Index));

            AssertSyntheticDomainCounts(Document);

            var DomainJson = DomainJsonSerializer.Serialize(Document);
            WriteSyntheticPackage(OutputPackage, "domain",
                Document.Domain.Id, Document.Domain.Name, Document.Domain.TechName,
                new SyntheticJsonPart("domain", JsonPackagePersistence.DomainJsonPartUri,
                                      DomainJsonDocument.CurrentFormat, DomainJson));
        }

        private static List<CompositionJsonIdea> BuildSyntheticConcepts(string CompositionId,
                                                                        SyntheticDefinitionSelection Definitions)
        {
            var Result = new List<CompositionJsonIdea>(SyntheticConceptCount);
            for (var Index = 0; Index < SyntheticConceptCount; Index++)
            {
                var Definition = Index < SyntheticConceptCount / 2
                               ? Definitions.OriginConcept
                               : Definitions.TargetConcept;
                Result.Add(new CompositionJsonIdea
                {
                    Id = SyntheticConceptId(Index),
                    Kind = "Concept",
                    Name = "Synthetic Concept " + Index.ToString("D4", CultureInfo.InvariantCulture),
                    TechName = SyntheticConceptTechName(Index),
                    Summary = "Deterministic concept " + Index.ToString(CultureInfo.InvariantCulture),
                    DefinitionId = Definition.Id,
                    DefinitionTechName = Definition.TechName,
                    DefinitionName = Definition.Name,
                    ContainerId = CompositionId,
                    ContainerTechName = "Synthetic_JSON_Persistence_Composition"
                });
            }
            return Result;
        }

        private static void BuildSyntheticView(CompositionJsonDocument Document, int ViewIndex,
                                               string CompositionId,
                                               SyntheticDefinitionSelection Definitions)
        {
            const int ConceptsPerRolePerView = 750;
            const int RelationshipsPerView = 1500;
            const int ConceptRolePopulation = SyntheticConceptCount / 2;

            var ViewId = StableGuid("synthetic-composition-view-" + ViewIndex.ToString("D4", CultureInfo.InvariantCulture));
            var View = new CompositionJsonView
            {
                Id = ViewId,
                Name = "Synthetic View " + ViewIndex.ToString("D2", CultureInfo.InvariantCulture),
                TechName = "Synthetic_View_" + ViewIndex.ToString("D2", CultureInfo.InvariantCulture),
                Summary = "Three thousand deterministic visual representations.",
                OwnerIdeaId = CompositionId,
                OwnerIdeaTechName = "Synthetic_JSON_Persistence_Composition"
            };

            var OriginIndexes = new int[ConceptsPerRolePerView];
            var TargetIndexes = new int[ConceptsPerRolePerView];
            var ConceptRepresentationIds = new Dictionary<int, string>();
            for (var Local = 0; Local < ConceptsPerRolePerView; Local++)
            {
                OriginIndexes[Local] = (ViewIndex * 500 + Local) % ConceptRolePopulation;
                TargetIndexes[Local] = ConceptRolePopulation + ((ViewIndex * 500 + Local) % ConceptRolePopulation);

                AddConceptVisual(View, ViewIndex, OriginIndexes[Local], Local, false, ConceptRepresentationIds);
                AddConceptVisual(View, ViewIndex, TargetIndexes[Local], Local, true, ConceptRepresentationIds);
            }

            for (var Local = 0; Local < RelationshipsPerView; Local++)
            {
                var RelationshipIndex = ViewIndex * RelationshipsPerView + Local;
                var OriginIndex = OriginIndexes[Local % ConceptsPerRolePerView];
                var TargetIndex = TargetIndexes[Local % ConceptsPerRolePerView];
                var Relationship = CreateSyntheticRelationship(RelationshipIndex, CompositionId,
                                                               OriginIndex, TargetIndex, Definitions);
                Document.Relationships.Add(Relationship);
                View.Visuals.Add(CreateRelationshipVisual(ViewIndex, Local, RelationshipIndex,
                                                          OriginIndex, TargetIndex, Relationship,
                                                          ConceptRepresentationIds, Definitions));
            }

            Document.Views.Add(View);
        }

        private static void AddConceptVisual(CompositionJsonView View, int ViewIndex, int ConceptIndex,
                                             int LocalIndex, bool IsTarget,
                                             IDictionary<int, string> RepresentationIds)
        {
            var RepresentationId = StableGuid("synthetic-concept-representation-" +
                ViewIndex.ToString("D2", CultureInfo.InvariantCulture) + "-" +
                ConceptIndex.ToString("D4", CultureInfo.InvariantCulture));
            RepresentationIds[ConceptIndex] = RepresentationId;

            View.Visuals.Add(new CompositionJsonVisual
            {
                IdeaId = SyntheticConceptId(ConceptIndex),
                IdeaTechName = SyntheticConceptTechName(ConceptIndex),
                RepresentationId = RepresentationId,
                ZOrder = IsTarget ? 750 + LocalIndex : LocalIndex,
                X = (LocalIndex % 30) * 220.0 + (IsTarget ? 80.0 : 0.0),
                Y = (LocalIndex / 30) * 140.0 + (IsTarget ? 5000.0 : 0.0),
                Width = 160.0,
                Height = 60.0
            });
        }

        private static CompositionJsonRelationship CreateSyntheticRelationship(int Index, string CompositionId,
                                                                                int OriginIndex, int TargetIndex,
                                                                                SyntheticDefinitionSelection Definitions)
        {
            var OriginLinkId = SyntheticRelationshipLinkId(Index, false);
            var TargetLinkId = SyntheticRelationshipLinkId(Index, true);
            var Result = new CompositionJsonRelationship
            {
                Id = SyntheticRelationshipId(Index),
                Kind = "Relationship",
                Name = "Synthetic Relationship " + Index.ToString("D4", CultureInfo.InvariantCulture),
                TechName = SyntheticRelationshipTechName(Index),
                Summary = "Deterministic relationship " + Index.ToString(CultureInfo.InvariantCulture),
                DefinitionId = Definitions.Relationship.Id,
                DefinitionTechName = Definitions.Relationship.TechName,
                DefinitionName = Definitions.Relationship.Name,
                ContainerId = CompositionId,
                ContainerTechName = "Synthetic_JSON_Persistence_Composition"
            };

            Result.OriginIdeaIds.Add(SyntheticConceptId(OriginIndex));
            Result.TargetIdeaIds.Add(SyntheticConceptId(TargetIndex));
            Result.Links.Add(new CompositionJsonRelationshipLink
            {
                Id = OriginLinkId,
                RoleType = Definitions.OriginRole.RoleType.NullDefault("Origin"),
                RoleDefinitionId = Definitions.OriginRole.Id,
                RoleDefinitionTechName = Definitions.OriginRole.TechName,
                RoleDefinitionName = Definitions.OriginRole.Name,
                IdeaId = SyntheticConceptId(OriginIndex),
                IdeaTechName = SyntheticConceptTechName(OriginIndex)
            });
            Result.Links.Add(new CompositionJsonRelationshipLink
            {
                Id = TargetLinkId,
                RoleType = Definitions.TargetRole.RoleType.NullDefault("Target"),
                RoleDefinitionId = Definitions.TargetRole.Id,
                RoleDefinitionTechName = Definitions.TargetRole.TechName,
                RoleDefinitionName = Definitions.TargetRole.Name,
                IdeaId = SyntheticConceptId(TargetIndex),
                IdeaTechName = SyntheticConceptTechName(TargetIndex)
            });
            return Result;
        }

        private static CompositionJsonVisual CreateRelationshipVisual(int ViewIndex, int LocalIndex,
                                                                      int RelationshipIndex,
                                                                      int OriginIndex, int TargetIndex,
                                                                      CompositionJsonRelationship Relationship,
                                                                      IDictionary<int, string> ConceptRepresentationIds,
                                                                      SyntheticDefinitionSelection Definitions)
        {
            var RelationshipRepresentationId = StableGuid("synthetic-relationship-representation-" +
                ViewIndex.ToString("D2", CultureInfo.InvariantCulture) + "-" +
                RelationshipIndex.ToString("D4", CultureInfo.InvariantCulture));
            var OriginRepresentationId = ConceptRepresentationIds[OriginIndex];
            var TargetRepresentationId = ConceptRepresentationIds[TargetIndex];
            var Result = new CompositionJsonVisual
            {
                IdeaId = Relationship.Id,
                IdeaTechName = Relationship.TechName,
                RepresentationId = RelationshipRepresentationId,
                ZOrder = 1500 + LocalIndex,
                X = (LocalIndex % 30) * 220.0 + 100.0,
                Y = (LocalIndex / 30) * 70.0 + 2450.0,
                Width = 40.0,
                Height = 40.0
            };

            Result.Connectors.Add(new CompositionJsonConnector
            {
                Id = StableGuid("synthetic-origin-connector-" + RelationshipIndex.ToString("D4", CultureInfo.InvariantCulture)),
                LinkId = Relationship.Links[0].Id,
                RoleType = Definitions.OriginRole.RoleType.NullDefault("Origin"),
                RoleDefinitionTechName = Definitions.OriginRole.TechName,
                AssociatedIdeaId = SyntheticConceptId(OriginIndex),
                AssociatedIdeaTechName = SyntheticConceptTechName(OriginIndex),
                ZOrder = 3000 + LocalIndex * 2,
                OriginRepresentationId = OriginRepresentationId,
                OriginIdeaId = SyntheticConceptId(OriginIndex),
                OriginIdeaTechName = SyntheticConceptTechName(OriginIndex),
                TargetRepresentationId = RelationshipRepresentationId,
                TargetIdeaId = Relationship.Id,
                TargetIdeaTechName = Relationship.TechName
            });
            Result.Connectors.Add(new CompositionJsonConnector
            {
                Id = StableGuid("synthetic-target-connector-" + RelationshipIndex.ToString("D4", CultureInfo.InvariantCulture)),
                LinkId = Relationship.Links[1].Id,
                RoleType = Definitions.TargetRole.RoleType.NullDefault("Target"),
                RoleDefinitionTechName = Definitions.TargetRole.TechName,
                AssociatedIdeaId = SyntheticConceptId(TargetIndex),
                AssociatedIdeaTechName = SyntheticConceptTechName(TargetIndex),
                ZOrder = 3001 + LocalIndex * 2,
                OriginRepresentationId = RelationshipRepresentationId,
                OriginIdeaId = Relationship.Id,
                OriginIdeaTechName = Relationship.TechName,
                TargetRepresentationId = TargetRepresentationId,
                TargetIdeaId = SyntheticConceptId(TargetIndex),
                TargetIdeaTechName = SyntheticConceptTechName(TargetIndex)
            });
            return Result;
        }

        private static CompositionJsonDomain BuildCompositionDomainContext(DomainJsonDocument DomainDocument,
                                                                            SyntheticDefinitionSelection Definitions)
        {
            var Source = DomainDocument.Domain;
            var Result = new CompositionJsonDomain
            {
                Id = Source.Id,
                Name = Source.Name,
                TechName = Source.TechName,
                Summary = Source.Summary,
                Description = Source.Description,
                TechSpec = Source.TechSpec,
                CompatibilitySignature = Source.CompatibilitySignature
            };

            foreach (var Definition in new[] { Definitions.OriginConcept, Definitions.TargetConcept }
                     .Where(Item => Item != null)
                     .GroupBy(Item => Item.TechName, StringComparer.OrdinalIgnoreCase)
                     .Select(Group => Group.First()))
                Result.Definitions.Add(ToCompositionDefinition(Definition, "ConceptDefinition"));
            Result.Definitions.Add(ToCompositionDefinition(Definitions.Relationship, "RelationshipDefinition"));
            return Result;
        }

        private static CompositionJsonDefinition ToCompositionDefinition(DomainJsonElement Source, string Kind)
        {
            return new CompositionJsonDefinition
            {
                Id = Source.Id,
                Kind = Kind,
                Name = Source.Name,
                TechName = Source.TechName,
                Summary = Source.Summary,
                Description = Source.Description,
                TechSpec = Source.TechSpec
            };
        }

        private static SyntheticDefinitionSelection SelectSyntheticDefinitions(DomainJsonDocument Document)
        {
            var Concepts = Document.ConceptDefinitions.Where(Item => Item != null && !String.IsNullOrWhiteSpace(Item.TechName)).ToList();
            var Relationships = Document.RelationshipDefinitions.Where(Item => Item != null && !String.IsNullOrWhiteSpace(Item.TechName)).ToList();
            if (Concepts.Count == 0 || Relationships.Count == 0)
                throw new InvalidDataException("The synthetic Composition seed Domain requires concept and relationship definitions.");

            var Relationship = Relationships.FirstOrDefault(Item => String.Equals(Item.TechName, "Relationship", StringComparison.OrdinalIgnoreCase))
                            ?? Relationships.FirstOrDefault(Item => Item.RoleDefinitions != null && Item.RoleDefinitions.Count >= 2)
                            ?? Relationships[0];
            var OriginRole = (Relationship.RoleDefinitions ?? new List<DomainJsonElement>())
                             .FirstOrDefault(Item => !String.Equals(Item.RoleType, "Target", StringComparison.OrdinalIgnoreCase));
            var TargetRole = (Relationship.RoleDefinitions ?? new List<DomainJsonElement>())
                             .FirstOrDefault(Item => String.Equals(Item.RoleType, "Target", StringComparison.OrdinalIgnoreCase));
            if (OriginRole == null || TargetRole == null)
                throw new InvalidDataException("The synthetic Composition relationship definition requires origin and target roles.");

            var Compatibility = (Document.RelationshipCompatibility ?? new List<DomainJsonRelationshipCompatibility>())
                                .FirstOrDefault(Item => String.Equals(Item.RelationshipDefinitionTechName,
                                                                      Relationship.TechName,
                                                                      StringComparison.OrdinalIgnoreCase));
            var DefaultConcept = Concepts.FirstOrDefault(Item => String.Equals(Item.TechName, "Concept", StringComparison.OrdinalIgnoreCase))
                              ?? Concepts[0];
            var OriginConcept = FindCompatibleConcept(Concepts, OriginRole.AssociableIdeaDefinitionTechNames,
                Compatibility == null ? null : Compatibility.AllowedOriginConceptDefinitionTechNames) ?? DefaultConcept;
            var TargetConcept = FindCompatibleConcept(Concepts, TargetRole.AssociableIdeaDefinitionTechNames,
                Compatibility == null ? null : Compatibility.AllowedTargetConceptDefinitionTechNames) ?? DefaultConcept;

            return new SyntheticDefinitionSelection
            {
                OriginConcept = OriginConcept,
                TargetConcept = TargetConcept,
                Relationship = Relationship,
                OriginRole = OriginRole,
                TargetRole = TargetRole
            };
        }

        private static DomainJsonElement FindCompatibleConcept(IEnumerable<DomainJsonElement> Concepts,
                                                               IEnumerable<string> RoleCandidates,
                                                               IEnumerable<string> CompatibilityCandidates)
        {
            var Requested = (RoleCandidates ?? Enumerable.Empty<string>())
                            .Concat(CompatibilityCandidates ?? Enumerable.Empty<string>())
                            .Where(Item => !String.IsNullOrWhiteSpace(Item))
                            .ToList();
            return Concepts.FirstOrDefault(Concept => Requested.Any(Item =>
                String.Equals(Item, Concept.TechName, StringComparison.OrdinalIgnoreCase)));
        }

        private static DomainJsonElement CreateSyntheticConceptDefinition(int Index)
        {
            return new DomainJsonElement
            {
                Id = StableGuid("synthetic-domain-concept-definition-" + Index.ToString("D4", CultureInfo.InvariantCulture)),
                Entity = "conceptDefinition",
                Name = "Synthetic Concept Definition " + Index.ToString("D3", CultureInfo.InvariantCulture),
                TechName = "Synthetic_Concept_Definition_" + Index.ToString("D3", CultureInfo.InvariantCulture),
                Summary = "Deterministic synthetic concept definition.",
                RepresentativeShape = "Rectangle",
                IsComposable = false,
                IsVersionable = false
            };
        }

        private static DomainJsonElement CreateSyntheticRelationshipDefinition(int Index)
        {
            var TechName = "Synthetic_Relationship_Definition_" + Index.ToString("D3", CultureInfo.InvariantCulture);
            var Result = new DomainJsonElement
            {
                Id = StableGuid("synthetic-domain-relationship-definition-" + Index.ToString("D4", CultureInfo.InvariantCulture)),
                Entity = "relationshipDefinition",
                Name = "Synthetic Relationship Definition " + Index.ToString("D3", CultureInfo.InvariantCulture),
                TechName = TechName,
                Summary = "Deterministic synthetic relationship definition.",
                RepresentativeShape = "Ellipse",
                IsDirectional = true,
                IsSimple = false,
                IsComposable = false,
                IsVersionable = false
            };
            Result.RoleDefinitions.Add(CreateSyntheticRole(Index, TechName, false));
            Result.RoleDefinitions.Add(CreateSyntheticRole(Index, TechName, true));
            return Result;
        }

        private static DomainJsonElement CreateSyntheticRole(int Index, string OwnerTechName, bool IsTarget)
        {
            var RoleName = IsTarget ? "Target" : "Origin";
            return new DomainJsonElement
            {
                Id = StableGuid("synthetic-domain-relationship-role-" + Index.ToString("D4", CultureInfo.InvariantCulture) + "-" + RoleName),
                Entity = "relationshipRole",
                Name = RoleName,
                TechName = RoleName,
                OwnerTechName = OwnerTechName,
                RoleType = RoleName,
                MaxConnections = UInt32.MaxValue,
                RelatedIdeasAreOrdered = false
            };
        }

        private static DomainJsonElement CreateSyntheticTableDefinition(int Index, string DataTypeTechName)
        {
            var TechName = "Synthetic_Table_" + Index.ToString("D3", CultureInfo.InvariantCulture);
            var Result = new DomainJsonElement
            {
                Id = StableGuid("synthetic-domain-table-" + Index.ToString("D4", CultureInfo.InvariantCulture)),
                Entity = "tableDefinition",
                Name = "Synthetic Table " + Index.ToString("D3", CultureInfo.InvariantCulture),
                TechName = TechName,
                Summary = "Deterministic eight-field table definition."
            };
            for (var FieldIndex = 0; FieldIndex < SyntheticDomainFieldsPerTable; FieldIndex++)
                Result.Fields.Add(new DomainJsonElement
                {
                    Id = StableGuid("synthetic-domain-table-field-" + Index.ToString("D4", CultureInfo.InvariantCulture) + "-" + FieldIndex.ToString("D2", CultureInfo.InvariantCulture)),
                    Entity = "fieldDefinition",
                    Name = "Field " + FieldIndex.ToString("D2", CultureInfo.InvariantCulture),
                    TechName = "Field_" + FieldIndex.ToString("D2", CultureInfo.InvariantCulture),
                    OwnerTechName = TechName,
                    DataTypeTechName = DataTypeTechName,
                    Order = FieldIndex
                });
            return Result;
        }

        private static DomainJsonElement CreateSyntheticMarkerDefinition(int Index)
        {
            return new DomainJsonElement
            {
                Id = StableGuid("synthetic-domain-marker-" + Index.ToString("D4", CultureInfo.InvariantCulture)),
                Entity = "markerDefinition",
                Name = "Synthetic Marker " + Index.ToString("D3", CultureInfo.InvariantCulture),
                TechName = "Synthetic_Marker_" + Index.ToString("D3", CultureInfo.InvariantCulture),
                Summary = "Deterministic synthetic marker."
            };
        }

        private static DomainJsonElement CreateSyntheticLanguage(int Index)
        {
            var Result = new DomainJsonElement
            {
                Id = StableGuid("synthetic-domain-language-" + Index.ToString("D2", CultureInfo.InvariantCulture)),
                Entity = "externalLanguage",
                Name = "Synthetic Language " + Index.ToString("D2", CultureInfo.InvariantCulture),
                TechName = "Synthetic_Language_" + Index.ToString("D2", CultureInfo.InvariantCulture),
                Summary = "Deterministic synthetic external language."
            };
            Result.Set["metaId"] = "synthetic-language-" + Index.ToString("D2", CultureInfo.InvariantCulture);
            return Result;
        }

        private static DomainJsonElement CreateSyntheticTemplate(int Index)
        {
            var Result = new DomainJsonElement
            {
                Id = StableGuid("synthetic-domain-template-" + Index.ToString("D3", CultureInfo.InvariantCulture)),
                Entity = "outputTemplate",
                Name = "Synthetic Template " + Index.ToString("D3", CultureInfo.InvariantCulture),
                TechName = "Synthetic_Template_" + Index.ToString("D3", CultureInfo.InvariantCulture),
                OwnerScope = "conceptDefinition",
                OwnerTechName = "Synthetic_Concept_Definition_" + Index.ToString("D3", CultureInfo.InvariantCulture),
                ExternalLanguageTechName = "Synthetic_Language_00",
                TemplateText = "%%:TemplateRole=Fragment\nSynthetic template " + Index.ToString("D3", CultureInfo.InvariantCulture) + ": {{ Idea.TechName }}\n",
                ExtendsBaseTemplate = false
            };
            Result.Set["templateRole"] = "Fragment";
            return Result;
        }

        private static string FindSeedFieldDataType(DomainJsonDocument Document)
        {
            return (Document.TableDefinitions ?? new List<DomainJsonElement>())
                   .Where(Table => Table != null)
                   .SelectMany(Table => Table.Fields ?? new List<DomainJsonElement>())
                   .Where(Field => Field != null && !String.IsNullOrWhiteSpace(Field.DataTypeTechName))
                   .Select(Field => Field.DataTypeTechName)
                   .FirstOrDefault() ?? "Text";
        }

        private static void AssertSyntheticCompositionCounts(CompositionJsonDocument Document)
        {
            var Visuals = Document.Views.Sum(View => View.Visuals.Count);
            var Connectors = Document.Views.Sum(View => View.Visuals.Sum(Visual => Visual.Connectors.Count));
            if (Document.Ideas.Count != SyntheticConceptCount ||
                Document.Relationships.Count != SyntheticRelationshipCount ||
                Document.Views.Count != SyntheticViewCount ||
                Visuals != SyntheticVisualCount || Connectors != SyntheticConnectorCount)
                throw new InvalidDataException("Synthetic Composition count assertion failed: concepts=" + Document.Ideas.Count +
                    ", relationships=" + Document.Relationships.Count + ", views=" + Document.Views.Count +
                    ", visuals=" + Visuals + ", connectors=" + Connectors + ".");
        }

        private static void AssertSyntheticDomainCounts(DomainJsonDocument Document)
        {
            var TemplateCount = Document.ConceptDefinitionOutputTemplates.Count +
                                Document.RelationshipDefinitionOutputTemplates.Count;
            if (Document.ConceptDefinitions.Count != SyntheticDomainConceptDefinitionCount ||
                Document.RelationshipDefinitions.Count != SyntheticDomainRelationshipDefinitionCount ||
                Document.TableDefinitions.Count != SyntheticDomainTableCount ||
                Document.TableDefinitions.Any(Table => Table == null || Table.Fields == null ||
                                                        Table.Fields.Count != SyntheticDomainFieldsPerTable) ||
                Document.MarkerDefinitions.Count != SyntheticDomainMarkerCount ||
                Document.ExternalLanguages.Count != SyntheticDomainLanguageCount ||
                TemplateCount != SyntheticDomainTemplateCount)
                throw new InvalidDataException("Synthetic Domain count assertion failed: concept definitions=" +
                    Document.ConceptDefinitions.Count + ", relationship definitions=" +
                    Document.RelationshipDefinitions.Count + ", tables=" + Document.TableDefinitions.Count +
                    ", markers=" + Document.MarkerDefinitions.Count + ", languages=" +
                    Document.ExternalLanguages.Count + ", templates=" + TemplateCount + ".");
        }

        private static void AssertCanonicalSyntheticPackageCounts(string PackagePath, string PackageKind)
        {
            if (String.Equals(PackageKind, "composition", StringComparison.OrdinalIgnoreCase))
            {
                var Payload = JsonPackagePersistence.ReadCompositionPackage(PackagePath);
                if (Payload == null || Payload.CompositionDocument == null)
                    throw new InvalidDataException("Canonical synthetic Composition has no authoritative /Composition.json payload.");

                AssertSyntheticCompositionCounts(Payload.CompositionDocument);
                return;
            }

            if (String.Equals(PackageKind, "domain", StringComparison.OrdinalIgnoreCase))
            {
                var Payload = JsonPackagePersistence.ReadDomainPackage(PackagePath);
                if (Payload == null || Payload.DomainDocument == null)
                    throw new InvalidDataException("Canonical synthetic Domain has no authoritative /Domain.json payload.");

                AssertCanonicalSyntheticDomainCounts(Payload.DomainDocument);
                return;
            }

            throw new InvalidDataException("Unsupported canonical synthetic package kind '" +
                                           PackageKind.ToStringAlways("<none>") + "'.");
        }

        private static void AssertCanonicalSyntheticDomainCounts(DomainJsonDocument Document)
        {
            var ConceptDefinitions = SyntheticElements(Document.ConceptDefinitions,
                                                        "Synthetic_Concept_Definition_");
            var RelationshipDefinitions = SyntheticElements(Document.RelationshipDefinitions,
                                                             "Synthetic_Relationship_Definition_");
            var Tables = SyntheticElements(Document.TableDefinitions, "Synthetic_Table_");
            var Markers = SyntheticElements(Document.MarkerDefinitions, "Synthetic_Marker_");
            var Languages = SyntheticElements(Document.ExternalLanguages, "Synthetic_Language_");
            var Templates = (Document.ConceptDefinitionOutputTemplates ?? new List<DomainJsonElement>())
                           .Concat(Document.RelationshipDefinitionOutputTemplates ?? new List<DomainJsonElement>())
                           .Where(IsCanonicalSyntheticTemplate)
                           .ToList();
            var InvalidTableFieldCounts = Tables.Count(Table => Table.Fields == null ||
                                                                 Table.Fields.Count != SyntheticDomainFieldsPerTable);
            var SyntheticFieldCount = Tables.Sum(Table => Table.Fields == null ? 0 : Table.Fields.Count);

            // Native Domain construction can retain system-owned defaults.  Count only the
            // deterministic Synthetic_* population so those defaults neither hide a loss nor
            // make an otherwise faithful canonicalization fail.
            if (ConceptDefinitions.Count != SyntheticDomainConceptDefinitionCount ||
                RelationshipDefinitions.Count != SyntheticDomainRelationshipDefinitionCount ||
                Tables.Count != SyntheticDomainTableCount || InvalidTableFieldCounts != 0 ||
                Markers.Count != SyntheticDomainMarkerCount ||
                Languages.Count != SyntheticDomainLanguageCount ||
                Templates.Count != SyntheticDomainTemplateCount)
                throw new InvalidDataException(
                    "Canonical synthetic Domain count assertion failed: synthetic concept definitions=" +
                    ConceptDefinitions.Count.ToString(CultureInfo.InvariantCulture) +
                    ", relationship definitions=" + RelationshipDefinitions.Count.ToString(CultureInfo.InvariantCulture) +
                    ", tables=" + Tables.Count.ToString(CultureInfo.InvariantCulture) +
                    ", fields=" + SyntheticFieldCount.ToString(CultureInfo.InvariantCulture) +
                    ", tables with non-eight field counts=" + InvalidTableFieldCounts.ToString(CultureInfo.InvariantCulture) +
                    ", markers=" + Markers.Count.ToString(CultureInfo.InvariantCulture) +
                    ", languages=" + Languages.Count.ToString(CultureInfo.InvariantCulture) +
                    ", templates=" + Templates.Count.ToString(CultureInfo.InvariantCulture) + ".");
        }

        private static bool IsCanonicalSyntheticTemplate(DomainJsonElement Item)
        {
            return Item != null &&
                   String.Equals(Item.OwnerScope, "conceptDefinition", StringComparison.OrdinalIgnoreCase) &&
                   !String.IsNullOrEmpty(Item.OwnerTechName) &&
                   Item.OwnerTechName.StartsWith("Synthetic_Concept_Definition_", StringComparison.Ordinal) &&
                   String.Equals(Item.ExternalLanguageTechName, "Synthetic_Language_00", StringComparison.Ordinal) &&
                   !String.IsNullOrEmpty(Item.TemplateText) &&
                   Item.TemplateText.StartsWith("%%:TemplateRole=Fragment\nSynthetic template ", StringComparison.Ordinal) &&
                   Item.ExtendsBaseTemplate == false;
        }

        private static List<DomainJsonElement> SyntheticElements(IEnumerable<DomainJsonElement> Source,
                                                                 string TechNamePrefix)
        {
            return (Source ?? Enumerable.Empty<DomainJsonElement>())
                   .Where(Item => Item != null &&
                                  !String.IsNullOrEmpty(Item.TechName) &&
                                  Item.TechName.StartsWith(TechNamePrefix, StringComparison.Ordinal))
                   .ToList();
        }

        private static void WriteSyntheticPackage(string OutputPackage, string PackageKind,
                                                  string SourceId, string SourceName, string SourceTechName,
                                                  params SyntheticJsonPart[] Parts)
        {
            if (Parts == null || Parts.Length == 0)
                throw new ArgumentException("A synthetic package requires at least one authoritative JSON part.", "Parts");

            OutputPackage = Path.GetFullPath(OutputPackage);
            EnsureParent(OutputPackage);
            using (var Package = System.IO.Packaging.Package.Open(OutputPackage, FileMode.Create, FileAccess.ReadWrite))
            {
                foreach (var Part in Parts)
                    WriteSyntheticPart(Package, Part.PartUri, Part.Bytes);

                var Manifest = BuildSyntheticManifest(PackageKind, SourceId, SourceName, SourceTechName, Parts);
                WriteSyntheticPart(Package, JsonPackagePersistence.ManifestPartUri,
                                   Utf8NoBom.GetBytes(Json.Serialize(Manifest)));
                Package.Flush();
            }
        }

        private static SortedDictionary<string, object> BuildSyntheticManifest(string PackageKind,
                                                                               string SourceId,
                                                                               string SourceName,
                                                                               string SourceTechName,
                                                                               IEnumerable<SyntheticJsonPart> Parts)
        {
            var AuthoritativeParts = Parts.Select(Part => (object)new SortedDictionary<string, object>(StringComparer.Ordinal)
            {
                { "bytes", Part.Bytes.LongLength },
                { "format", Part.Format },
                { "kind", Part.Kind },
                { "partUri", Part.PartUri.ToString() },
                { "sha256", HashBytes(Part.Bytes) }
            }).ToList();

            return new SortedDictionary<string, object>(StringComparer.Ordinal)
            {
                { "application", "ThinkComposer" },
                { "applicationVersion", "performance-corpus-1" },
                { "authoritativeParts", AuthoritativeParts },
                { "format", "ThinkComposer.Package" },
                { "formatVersion", 1 },
                { "legacyBinaryFallback", new SortedDictionary<string, object>(StringComparer.Ordinal) { { "present", false } } },
                { "packageKind", PackageKind },
                { "persistenceFormat", "json" },
                { "persistenceFormatVersion", 1 },
                { "savedAtUtc", SyntheticTimestamp },
                { "sidecars", new SortedDictionary<string, object>(StringComparer.Ordinal) { { "interchangeManifestUri", "/Interchange/manifest.json" } } },
                { "source", new SortedDictionary<string, object>(StringComparer.Ordinal)
                    {
                        { "id", SourceId },
                        { "name", SourceName },
                        { "summary", "Deterministic JSON persistence performance corpus." },
                        { "techName", SourceTechName }
                    }
                },
                { "warnings", new List<string>() }
            };
        }

        private static void WriteSyntheticPart(Package Package, Uri PartUri, byte[] Bytes)
        {
            if (Package.PartExists(PartUri))
                Package.DeletePart(PartUri);
            var Part = Package.CreatePart(PartUri, JsonContentType, CompressionOption.Maximum);
            using (var Stream = Part.GetStream(FileMode.Create, FileAccess.Write))
                Stream.Write(Bytes, 0, Bytes.Length);
        }

        private static string SyntheticConceptId(int Index)
        {
            return StableGuid("synthetic-concept-" + Index.ToString("D4", CultureInfo.InvariantCulture));
        }

        private static string SyntheticConceptTechName(int Index)
        {
            return "Synthetic_Concept_" + Index.ToString("D4", CultureInfo.InvariantCulture);
        }

        private static string SyntheticRelationshipId(int Index)
        {
            return StableGuid("synthetic-relationship-" + Index.ToString("D4", CultureInfo.InvariantCulture));
        }

        private static string SyntheticRelationshipTechName(int Index)
        {
            return "Synthetic_Relationship_" + Index.ToString("D4", CultureInfo.InvariantCulture);
        }

        private static string SyntheticRelationshipLinkId(int Index, bool IsTarget)
        {
            return StableGuid("synthetic-relationship-link-" + Index.ToString("D4", CultureInfo.InvariantCulture) +
                              (IsTarget ? "-target" : "-origin"));
        }

        private static string StableGuid(string Seed)
        {
            using (var Hash = SHA256.Create())
            {
                var Digest = Hash.ComputeHash(Encoding.UTF8.GetBytes("ThinkComposer.JsonPersistenceCorpus/" + Seed));
                var Bytes = new byte[16];
                Array.Copy(Digest, Bytes, Bytes.Length);
                return new Guid(Bytes).ToString("D");
            }
        }

        private sealed class SyntheticDefinitionSelection
        {
            public DomainJsonElement OriginConcept;
            public DomainJsonElement TargetConcept;
            public DomainJsonElement Relationship;
            public DomainJsonElement OriginRole;
            public DomainJsonElement TargetRole;
        }

        private sealed class SyntheticJsonPart
        {
            public readonly string Kind;
            public readonly Uri PartUri;
            public readonly string Format;
            public readonly byte[] Bytes;

            public SyntheticJsonPart(string Kind, Uri PartUri, string Format, string JsonText)
            {
                this.Kind = Kind;
                this.PartUri = PartUri;
                this.Format = Format;
                this.Bytes = Utf8NoBom.GetBytes(JsonText ?? "");
            }
        }
    }
}
