<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Instrumind.Common</RootNamespace>
    <AssemblyName>Instrumind.Common</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Configurations>CD_ROM;Debug;DVD-5;Release;SingleImage</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Platform\**\*.cs" />
    <Compile Include="Portable\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Packaging" Version="10.0.9" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.9" />
  </ItemGroup>
</Project>
